apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcluster-rancher-op
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: vcluster-rancher-op
    app.kubernetes.io/name: vcluster-rancher-op
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: vcluster-rancher-op
      app.kubernetes.io/name: vcluster-rancher-op
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: vcluster-rancher-op
        app.kubernetes.io/name: vcluster-rancher-op
    spec:
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: manager
        image: "{{ template "default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
        ports: []
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: vcluster-rancher-op
      terminationGracePeriodSeconds: 10
